server:
  port: 8084

spring:
  cors:
    allowed-origins: http://localhost:5173
  # spring data jpa 설정
#  profiles:
#    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/dogcatdang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update