server:
  port: 8084
#  ssl:
#    key-store: keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ssafy202

# database 연동 설정
spring:
  jwt:
    secret: sadofinwdfjadfndkjsfnsdfjklsdjfansdjkfasdisdfkslasdifklsdanflaksdjfnasdkjfnasdifasdnfkjasdlfnsdf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dogcatdang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# s3 서버 설정
cloud:
  aws:
    s3:
      bucket: dogcatdang
    credentials:
      access-key: AKIATCKAM24E3GBXXP4N
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
